"use client";
import { useEffect, useState } from "react";

type Project = { project: string; latestCheckpoint: string | null; checkpointCount: number; contextStatus: "COMPLETE" | "PARTIAL" | "INSUFFICIENT"; unavailableFields: string[]; intent: { intentCoverage: number | null; unfinished: string[]; risks: string[]; status?: string }; integrations: { entire: string; databricks: string } };
type Result = { title: string; value: unknown } | null;
const api = async (url: string, options?: RequestInit) => { const response = await fetch(url, options); return response.json(); };
const pretty = (value: unknown) => JSON.stringify(value, null, 2);

export default function Home() {
  const [project, setProject] = useState<Project | null>(null); const [result, setResult] = useState<Result>(null);
  const [target, setTarget] = useState("src/payment/service.ts"); const [query, setQuery] = useState("Why was Redis introduced?"); const [loading, setLoading] = useState<string | null>(null);
  const refresh = async () => setProject(await api("/api/project"));
  useEffect(() => { refresh(); }, []);
  const run = async (title: string, url: string, body?: unknown) => { setLoading(title); try { const value = await api(url, { method: "POST", headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); setResult({ title, value }); await refresh(); } finally { setLoading(null); } };
  const coverage = project?.intent.intentCoverage;
  return <main>
    <aside className="side"><div className="brand"><span className="dot" /> CODEBASE<br />BLACK BOX</div><nav><a className="active">Overview</a><a href="#intent">Intent review</a><a href="#impact">Impact analysis</a><a href="#timeline">Checkpoint timeline</a></nav><div className="integration"><p>INTEGRATIONS</p><span className={project?.integrations.entire.includes("detected") ? "warn" : "ok"}>● Entire</span><small>{project?.integrations.entire || "Checking…"}</small><span className={project?.integrations.databricks === "configured" ? "ok" : "warn"}>● Databricks</span><small>{project?.integrations.databricks || "Checking…"}</small></div></aside>
    <section className="shell"><header><div><p className="eyebrow">DEVELOPMENT FLIGHT RECORDER</p><h1>Project overview</h1><p className="muted">{project?.project || "Loading project evidence…"}</p></div><button className="outline" onClick={() => run("Entire checkpoint refresh", "/api/checkpoints/refresh")}>↻ Refresh Entire</button></header>
      <div className="notice"><span>◇</span><div><strong>Evidence before inference.</strong> This dashboard only makes development claims backed by Entire, Databricks, or test evidence. Missing evidence stays visible.</div></div>
      <div className={`context ${project?.contextStatus?.toLowerCase() || "insufficient"}`}><span>●</span><div><strong>CONTEXT {project?.contextStatus || "INSUFFICIENT"}</strong><p>{project?.contextStatus === "COMPLETE" ? "Analysis based on complete checkpoint context." : project?.contextStatus === "PARTIAL" ? "Some checkpoint information is unavailable. Results are based only on available evidence." : "Not enough evidence for an authoritative conclusion."}</p>{project?.unavailableFields.length ? <small>Unavailable: {project.unavailableFields.join(", ")}</small> : null}</div></div>
      <section className="metrics"><Metric label="INTENT COVERAGE" value={coverage === null || coverage === undefined ? "—" : `${coverage}%`} sub={project?.intent.status || "From latest Entire checkpoint"} /><Metric label="RISK" value={project?.intent.risks.length ? "OPEN" : "—"} sub={project?.intent.risks.length ? `${project.intent.risks.length} checkpoint risk(s)` : "No verified risk record"} /><Metric label="UNFINISHED" value={String(project?.intent.unfinished.length || 0)} sub="Explicit checkpoint requirements" /><Metric label="RECENT CHECKPOINT" value={project?.latestCheckpoint || "—"} sub={`${project?.checkpointCount || 0} locally retained`} /></section>
      <section className="actions"><Action title="Review Intent" copy="Extract completed work, unfinished requirements, decisions, and known risks." onClick={() => run("Intent review", "/api/intent/analyze")} loading={loading === "Intent review"} /><Action title="Analyze Impact" copy="Use Entire Graph structural evidence for a selected file or function." onClick={() => run("Impact analysis", "/api/impact/analyze", { target })} loading={loading === "Impact analysis"} /><Action title="Resume Work" copy="Generate a copyable, evidence-bound continuation task for a new agent session." onClick={() => run("Agent continuation", "/api/resume")} loading={loading === "Agent continuation"} /></section>
      <section id="impact" className="panel input-panel"><div><p className="eyebrow">ENTIRE GRAPH</p><h2>Inspect a code change</h2></div><div className="input-row"><input aria-label="File or symbol" value={target} onChange={(event) => setTarget(event.target.value)} /><button onClick={() => run("Impact analysis", "/api/impact/analyze", { target })}>Analyze</button></div><p>Graph relationships are shown as evidence, not treated as an oracle.</p></section>
      <section id="intent" className="two"><div className="panel"><p className="eyebrow">DATABRICKS AI SEARCH</p><h2>Ask development memory</h2><div className="input-row"><input aria-label="Memory question" value={query} onChange={(event) => setQuery(event.target.value)} /><button onClick={() => run("Memory search", "/api/memory/search", { query })}>Search</button></div><p>Historical development events take priority over generic answers.</p></div><div className="panel curve"><p className="eyebrow">CURVEBALL MODE</p><h2>Fresh session, verified context</h2><p>Restore the latest checkpoint, decisions, unfinished work and graph impact into a safe continuation prompt.</p><button className="outline" onClick={() => run("Curveball continuation", "/api/resume")}>Prepare handoff</button></div></section>
      <section id="timeline" className="panel timeline"><p className="eyebrow">CHECKPOINT TIMELINE</p><h2>Development memory</h2><p>{project?.checkpointCount ? `${project.checkpointCount} checkpoint(s) available. Open the timeline API for the full source record.` : "No checkpoint evidence imported yet. Connect Entire CLI, then click Refresh Entire, or import a real checkpoint JSON record."}</p><button className="text-button" onClick={() => run("Checkpoint timeline", "/api/timeline")}>View source timeline →</button></section>
      {result && <section className="result"><div className="result-head"><div><p className="eyebrow">EVIDENCE OUTPUT</p><h2>{result.title}</h2></div><button className="outline" onClick={() => navigator.clipboard.writeText(pretty(result.value))}>Copy</button></div><pre>{pretty(result.value)}</pre></section>}
    </section>
  </main>;
}
function Metric({ label, value, sub }: { label: string; value: string; sub: string }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{sub}</small></article>; }
function Action({ title, copy, onClick, loading }: { title: string; copy: string; onClick: () => void; loading: boolean }) { return <article className="action"><div className="action-icon">↗</div><h2>{title}</h2><p>{copy}</p><button onClick={onClick} disabled={loading}>{loading ? "Working…" : "Open workflow"}</button></article>; }
